# Generated by Django 5.0.6 on 2024-05-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlquerry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
